{
 "title": "OPC UA Machine Overview",
 "tags": [
  "opcua",
  "prototype"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "bucket", "query": "machine-data" },
   { "name": "measurement", "query": "opcua_metrics" },
   { "name": "machine", "label": "Machine", "query": "machine_1" }
  ]
 },
 "panels": [
  {
   "title": "Latest E_10_Jena Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -24h, stop: now())\n  |> filter(fn: (r) => r._measurement == \"${measurement}\")\n  |> filter(fn: (r) => r._field == \"value_str\")\n  |> filter(fn: (r) => r.machine == \"${machine}\")\n  |> filter(fn: (r) => r.node_id =~ /E_10_Jena/)\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n  |> keep(columns: [\"_time\", \"_value\", \"node_id\"])"
    }
   ]
  },
  {
   "title": "Temperatur Wanne 9",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -24h, stop: now())\n  |> filter(fn: (r) => r._measurement == \"${measurement}\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.machine == \"${machine}\")\n  |> filter(fn: (r) => r.node_id =~ /Temperatur/)\n  |> filter(fn: (r) => r.node_id =~ /Wanne_09/)\n  |> group(columns: [\"node_id\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> fill(usePrevious: true)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Leitwert Wanne 9",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -24h, stop: now())\n  |> filter(fn: (r) => r._measurement == \"${measurement}\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.machine == \"${machine}\")\n  |> filter(fn: (r) => r.node_id =~ /ST10_Wanne_09/ )\n  |> filter(fn: (r) => r.node_id =~ /Leitwert/ )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> fill(usePrevious: true)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature Wanne 12",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -24h, stop: now())\n  |> filter(fn: (r) => r._measurement == \"${measurement}\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.machine == \"${machine}\")\n  |> filter(fn: (r) => r.node_id =~ /Temperatur/)\n  |> filter(fn: (r) => r.node_id =~ /Wanne_12/)\n  |> group(columns: [\"node_id\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> fill(usePrevious: true)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Leitwert Wanne 12",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -24h, stop: now())\n  |> filter(fn: (r) => r._measurement == \"${measurement}\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.machine == \"${machine}\")\n  |> filter(fn: (r) => r.node_id =~ /ST13_Wanne_12/ )\n  |> filter(fn: (r) => r.node_id =~ /Leitwert/ )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> fill(usePrevious: true)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}